import type { MazeModel, MazeSettings } from '../core/types';
import { getPageSize } from '../core/geometry';
import { getTheme } from '../themes';
import { scaleToFit } from '../transform/scaleToFit';
import { rotateMazeTransform } from '../transform/rotateMaze';
import { renderMazeSvg } from './renderMazeSvg';
import { renderDecorationsSvg } from './renderDecorationsSvg';
export function renderPageSvg(settings: MazeSettings, model: MazeModel, forceSolution?: boolean): string { const page = getPageSize(settings); const theme = getTheme(settings.theme, settings.visualMode); const margin = Math.max(42, Math.min(page.width, page.height) * .065); const headerH = page.height * .18; const footerH = page.height * .1; const safeW = page.width - margin * 2; const safeH = page.height - margin * 2 - headerH - footerH; const mazeW = model.type === 'circle' ? Math.min(safeW, safeH) : safeW; const mazeH = model.type === 'circle' ? mazeW : safeH; const x = (page.width - mazeW) / 2; const y = margin + headerH; const angle = settings.rotateMazeOnly ? settings.rotationAngle : 0; const sc = scaleToFit(mazeW, mazeH, angle); const effective = { ...settings, showSolution: forceSolution ?? settings.showSolution }; const content = renderMazeSvg(model, effective, theme, mazeW, mazeH); const mazeGroup = `<g transform="${rotateMazeTransform(x + mazeW/2, y + mazeH/2, mazeW, mazeH, angle, sc)}">${content}</g>`; const body = `<rect width="100%" height="100%" fill="${theme.background}"/><rect x="${margin/2}" y="${margin/2}" width="${page.width-margin}" height="${page.height-margin}" rx="28" fill="none" stroke="${theme.accent}" stroke-width="3" stroke-dasharray="${settings.visualMode==='coloring'?'0':'10 12'}"/>${renderDecorationsSvg(page.width,page.height,settings,theme)}<text x="${margin}" y="${margin+40}" font-size="${Math.max(32,page.width*.045)}" font-weight="800" fill="${theme.text}">${escapeXml(settings.title)}</text><text x="${margin}" y="${margin+78}" font-size="${Math.max(18,page.width*.022)}" fill="${theme.text}">${escapeXml(settings.instruction)}</text><text x="${page.width-margin}" y="${margin+35}" text-anchor="end" font-size="18" fill="${theme.text}">Задание №${settings.taskNumber}</text><text x="${margin}" y="${page.height-margin*.55}" font-size="20" fill="${theme.text}">Имя: ____________________</text><text x="${page.width-margin}" y="${page.height-margin*.55}" text-anchor="end" font-size="18" fill="${theme.text}">${settings.startLabel} → ${settings.finishLabel}</text>${mazeGroup}`; const full = settings.rotateFullComposition ? `<g transform="translate(${page.width/2} ${page.height/2}) rotate(${settings.rotationAngle}) scale(${scaleToFit(page.width,page.height,settings.rotationAngle)}) translate(${-page.width/2} ${-page.height/2})">${body}</g>` : body; return `<svg id="worksheet-svg" xmlns="http://www.w3.org/2000/svg" width="${page.width}" height="${page.height}" viewBox="0 0 ${page.width} ${page.height}" role="img" aria-label="Maze Worksheet Studio page">${full}</svg>`; }
function escapeXml(s: string) { return s.replace(/[<>&"']/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]!)); }
